# Generated by Django 5.1.6 on 2025-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('WALLET_CREATE', 'Création portefeuille'), ('WALLET_DELETE', 'Suppression portefeuille'), ('TRANSACTION_CREATE', 'Ajout transaction'), ('TRANSACTION_DELETE', 'Suppression transaction'), ('OBJECTIVE_UPDATE', 'Modification objectif'), ('USER_REGISTER', 'Inscription utilisateur'), ('PASSWORD_CHANGE', 'Changement mot de passe'), ('PROFILE_UPDATE', 'Modification profil'), ('ERROR', 'Erreur'), ('ADMIN_ACTION', 'Action admin'), ('OTHER', 'Autre')], max_length=50),
        ),
    ]
