# Generated by Django 5.1.6 on 2025-05-26 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('WALLET_CREATE', 'Création portefeuille'), ('WALLET_DELETE', 'Suppression portefeuille'), ('WALLET_UPDATE', 'Modification portefeuille'), ('TRANSACTION_CREATE', 'Ajout transaction'), ('TRANSACTION_DELETE', 'Suppression transaction'), ('TRANSACTION_UPDATE', 'Modification transaction'), ('OBJECTIVE_UPDATE', 'Modification objectif'), ('USER_REGISTER', 'Inscription utilisateur'), ('PASSWORD_CHANGE', 'Changement mot de passe'), ('ERROR', 'Erreur'), ('ADMIN_ACTION', 'Action admin'), ('OTHER', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
