# Generated by Django 5.1.6 on 2025-05-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_event_user_name_snapshot_alter_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('WALLET_CREATE', 'Création portefeuille'), ('WALLET_DELETE', 'Suppression portefeuille'), ('WALLET_UPDATE', 'Modification portefeuille'), ('TRANSACTION_CREATE', 'Ajout transaction'), ('TRANSACTION_DELETE', 'Suppression transaction'), ('TRANSACTION_UPDATE', 'Modification transaction'), ('TRANSACTION_EXPORT', 'Export transaction'), ('OBJECTIVE_UPDATE', 'Modification objectif'), ('USER_REGISTER', 'Inscription utilisateur'), ('PASSWORD_CHANGE', 'Changement mot de passe'), ('ERROR', 'Erreur'), ('ADMIN_ACTION', 'Action admin'), ('OTHER', 'Autre')], max_length=50),
        ),
    ]
