# Generated by Django 5.1.6 on 2025-05-27 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('LOGIN', 'event_type_login'), ('LOGOUT', 'event_type_logout'), ('WALLET_CREATE', 'event_type_wallet_create'), ('WALLET_DELETE', 'event_type_wallet_delete'), ('WALLET_UPDATE', 'event_type_wallet_update'), ('TRANSACTION_CREATE', 'event_type_transaction_create'), ('TRANSACTION_DELETE', 'event_type_transaction_delete'), ('TRANSACTION_UPDATE', 'event_type_transaction_update'), ('TRANSACTION_EXPORT', 'event_type_transaction_export'), ('OBJECTIVE_UPDATE', 'event_type_objective_update'), ('USER_REGISTER', 'event_type_user_register'), ('PASSWORD_CHANGE', 'event_type_password_change'), ('ERROR', 'event_type_error'), ('ADMIN_ACTION', 'event_type_admin_action'), ('OTHER', 'event_type_other')], max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user_name_snapshot',
            field=models.CharField(blank=True, max_length=255, verbose_name='user_name_snapshot'),
        ),
    ]
