# Generated by Django 5.1.6 on 2025-06-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_event_options_alter_event_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('LOGIN', 'event_type_login'), ('LOGOUT', 'event_type_logout'), ('WALLET_CREATE', 'event_type_wallet_create'), ('WALLET_DELETE', 'event_type_wallet_delete'), ('WALLET_UPDATE', 'event_type_wallet_update'), ('TRANSACTION_CREATE', 'event_type_transaction_create'), ('TRANSACTION_DELETE', 'event_type_transaction_delete'), ('TRANSACTION_UPDATE', 'event_type_transaction_update'), ('TRANSACTION_EXPORT', 'event_type_transaction_export'), ('OBJECTIVE_UPDATE', 'event_type_objective_update'), ('USER_REGISTER', 'event_type_user_register'), ('PASSWORD_CHANGE', 'event_type_password_change'), ('ERROR', 'event_type_error'), ('ADMIN_ACTION', 'event_type_admin_action'), ('OTHER', 'event_type_other'), ('REPORT_GENERATE', 'event_type_report_generate')], max_length=50, verbose_name='type'),
        ),
    ]
