# Generated by Django 5.2.1 on 2025-06-15 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20250615_1318'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_income', models.BooleanField(default=False, verbose_name='is_income')),
                ('execution_date', models.DateTimeField(verbose_name='execution date')),
                ('frequency', models.CharField(choices=[('once', 'once'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='once', max_length=10, verbose_name='frequency')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.category', verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_transactions', to='wallet.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'future transaction',
                'verbose_name_plural': 'future transactions',
            },
        ),
    ]
