# Generated by Django 5.1.6 on 2025-06-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_futuretransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='objective',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='objective'),
        ),
    ]
