# Generated by Django 5.1.6 on 2025-05-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
